### ISSUE TITLE
Shop items don't display (for some users)

### ISSUE THREAD

**Issue by aprilkae** [ESX-Org/esx_shops#13]
This happens randomly and with random shops, shop menu will open but the shop menu is empty when there are items available for someone else. F8 error says 'Cannot read property 'scrollIntoView' of undefined.

**Comment by sirmarknlddr** [comment]
Happens on our server as well. Strange since some people have this issue and some people don't. Happened since the last update.

**Comment by TemptressTeelia** [comment]
This is happening on our server as well.  
I have purchased items from a 24/7. Then someone has come in and not seen it all. Then another person came over to double check and food was there. 
No idea why.

**Comment by ElPumpo** [comment]
How about now? The script has been improved

**Comment by aprilkae** [comment]
I haven't had a problem since the update (updated a few days ago) - but I'll update it to the latest version you put out and see how it works.

**Comment by ElPumpo** [comment]
##Important note
The column name inside shops has been renamed to store, so make sure you change it up, or else problems will occur

**Comment by aprilkae** [comment]
Ah, that was probably the cause. I’ll download the latest again and update the db column name and let you know.

**Comment by yaukzzz** [comment]
I've made a clean install of shops and the issue still persists. Any ideas?

**Comment by qalleh1** [comment]
Yes, change the column name as staded by ElPump, change name to store in DB

**Comment by yaukzzz** [comment]
I've changed that, made a clean install and installed it as the instructions. Still not working.

**Comment by sesipod** [comment]
Currently not working for me either frsh server install. I get the shop menu (bottom right) but no items are populated in the listing. 

Database is correct. Imported the SQL file included with the latest download. 

F8 reports : Cannot read property 'scrollIntoView' of undefined

All shops are broken.

**Comment by yaukzzz** [comment]
Same problem on my server

**Comment by Nurfey** [comment]
Same for me, I can press E but nothing shows up.

**Comment by ElPumpo** [comment]
Obviously I cannot reproduce this. Unless someone steps up and at least tries to debug what's going on it will never be solved.

Also commenting 'same' or similar is classed as spam, use emotes instead.

**Comment by sesipod** [comment]
I got the shop working by re-doing the Items database. 
By default ESX now installs the items table in the DB without the ( ID ) section. 

I created the ID block set it as primary and added Water and Bread as a test rebooted the server and now its allowing me to buy items. 

Here is an export of my SQL table for Items. Please make a backup of your items before using my sql file.
[items.zip](https://github.com/ESX-Org/esx_shops/files/2133533/items.zip)

![items](https://user-images.githubusercontent.com/1533744/41856401-9c8c347c-785a-11e8-82a2-fb1e9452f215.JPG)
![shops](https://user-images.githubusercontent.com/1533744/41856402-9ca47b0e-785a-11e8-8ab7-97e098af76c1.JPG)

**Comment by Bezz1** [comment]
yeah it's fucked

**Comment by Harmarz** [comment]
error received with current build, everything default sometimes will work sometimes will not, markers will sometimes flash indication there may be a slowdown in the script
https://i.gyazo.com/efe5665b59c5c9130b1bd31d696382c6.png

**Comment by NinjaMuffin08** [comment]
For me the shops still do not clear if cache gets cleared. In my F8 Menu I see these errors.
https://pastebin.com/3apubDfq

along with the error involving esx menu default. 
EndpointMapper:: HandleRequest: Post /gta5/11/gameservices/GeoLocation.asmx/GetLocationInfoFromIP
nui://esx_menu_deafault/html/js/app.js:64, Uncaught TypeError: Cannot read property 'scrollIntoView' of undefined

Which i believe the pastebin error is more revelant and the endpoint mapper error seen above is just a byproduct of it.

**Comment by NinjaMuffin08** [comment]
name to store  leads to a half and half issue. Some players get the shops Some players will not get the shop. It also depends what shop location works. Like all of em could work for 1 person but none except 2 locations work. 

so no the topic needs to remain open

**Comment by deviljin112** [comment]
Well i've tried to recreate your problem but with a team of 10 people we tried each shop every single person has tried it, no one has a problem, i've renamed the db and cleared cache and its all working on 3 of my servers + test server :)

**Comment by TemptressTeelia** [comment]
Just tested this again, and unless I clear cache I will get shops not loading items for some people. This also applies for weapons and cars as well. This has to be an extended problem as it effects all items being called from DB.

**Comment by NinjaMuffin08** [comment]
Deviljin I'm glad it's working for your servers but my issue is i can do a complete server wipe and reinstall the basics with zap's files and with nothing else added it is busted with 6 people testing it.

One thought is maybe one of the versions of the basic files are different and that's why we are yielding different results?

**Comment by NinjaMuffin08** [comment]
@TemptressTeelia  Do you have any duplicates in your database?

**Comment by TemptressTeelia** [comment]
Oh. Sorry. This is working for me. I uninstalled mod. ;) I use shop with bars and if it doesn’t show I clear cache. Works fully.

**Comment by EGUltraTM** [comment]
For me this still happens. 

using only the original esx_shops script.

I cant see for example the LTDGasoline shops items but all the others. Some other users see the LTDGasoline but some others not. Thats wierd

**Comment by NinjaMuffin08** [comment]
@EGUltraTM  If you have duplicates in your item database it can cause the issue.

**Comment by nagpain** [comment]
i have same problem, any help me
https://prnt.sc/lbas44

**Comment by NinjaMuffin08** [comment]
@cantfish are your shop items also items in the items table?

**Comment by cooki143** [comment]
I have tried doing everything people have suggested, nothing seems to permanently work. 
The only thing that helped was clearing the cache, it would let it work up to a few restarts before all the items disappeared completely. 
Anyone have a suggestion?

**Comment by Ranger194** [comment]
i have the same problem, i put new DB files everything and nothing happen, now doesnt appear any items on shop

**Comment by cooki143** [comment]
I don't know if I'm allowed to share this in this issue,  but no matter what I tried I Couldn't get ESX_shop to display items.

I switched to esx_supermarket and it works great. Haven't had an issue yet

**Comment by deltaforce168** [comment]
> Yes, change the column name as staded by ElPump, change name to store in DB

my DB says store and it is still having this problems any other fix you can throw out there please

**Comment by eljrp** [comment]
I renamed my DB table "shops" to "store" and changed the client and server lua to pull from "store". I think it may have something to do with onesync. Not 100% sure why but it worked fine until I upgraded my server.
