### ISSUE TITLE
Unable to choose quantity

### ISSUE THREAD

**Issue by garagevive** [ESX-Org/esx_shops#18]
I am probably just missing something but how can you purchase more than one item from a shop? I can only purchase 1 item. Have tried arrows, +/-, page up/down, mouse wheel... what am I missing?

**Comment by ElPumpo** [comment]
it's a slider ffs, left and right arrows

**Comment by Hoplox** [comment]
Left and Right arrows don't seem to work, i have this issue too. Same for my players.
