### ISSUE TITLE
Arrow Keys Don't Select Quantity to Purchase in Shop

### ISSUE THREAD

**Issue by garagevive** [ESX-Org/esx_shops#19]
Multiple servers/users having the issue where arrow keys do not select quantity (no way to increase from 1).

**Comment by xnubil** [comment]
it doesn't work with unlimited quantities, if you give your shop items a limits, the arrow keys work

**Comment by sesipod** [comment]
I will test this tommorow 😊 thanks for the heads up
@xnubil

**Comment by garagevive** [comment]
Adding a limit in items table fixed the issue, I can confirm :)

**Comment by ElPumpo** [comment]
Don't close this issue yet. Gotta remove the `max` metadata if the item limit is unlimited.
