### ISSUE TITLE
Shop issues with the new updates

### ISSUE THREAD

**Issue by nykroza** [ESX-Org/esx_shops#22]
![unknown](https://user-images.githubusercontent.com/40612847/42807144-01d3b52e-897e-11e8-923d-7fe3fb429726.png)

**Comment by tunnelrat327** [comment]
Just remove:
    
```lua
if itemInformation[shopResult[i].item].limit == -1 then
    itemInformation[shopResult[i].item].limit = 30
end
```

And (a) Replace the -1 values in your database or (b) Replace negative values in .sql file and import. Make sure you set those values to 30 for items you want to use.

**Comment by baalexan** [comment]
And line 70 comment 

amout = ESX.round(amount)

**Comment by Hunt3red** [comment]
I fixed it!

All you have to do is go to the "items" table, and add bread and water! Simple
