### ISSUE TITLE
Shops issue

### ISSUE THREAD

**Issue by turnhama70** [ESX-Org/esx_shops#24]
Error running system event handling function for resource esx_shops: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:43: attempt to index a nil value (field '?')
stack traceback:
        server/main.lua:43: in function 'LoadShop'
        server/main.lua:10: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>

please help i don't know why its coming up with this error.

**Comment by EisonCheng** [comment]
Add esx_basicneeds and esx_status is working
