### ISSUE TITLE
Waypoints + Blips.

### ISSUE THREAD

**Issue by Detoxz** [ESX-Org/esx_shops#25]
Placing a waypoint automatically locks on to closest shop on map. Anyway to resolve this?

**Comment by ElPumpo** [comment]
Do you have an old version of the esx_atm script? Show a screenshot of your map with the blip list to the right

**Comment by TemptressTeelia** [comment]
If I remembered rightly this was solved, it was esx shops conflicting with the waypoints. He uninstalled it and it worked if I recall.
