### ISSUE TITLE
esx_shops: citizen:/scripting/lua/scheduler.lua:41

### ISSUE THREAD

**Issue by hydrocut** [ESX-Org/esx_shops#26]
Bonjour

Je rencontre un probleme sur mon serveur avec votre extention esx_shop

Voici le code d'erreur : 
`Error running system event handling function for resource esx_shops: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:43: attempt to index a nil value (field '?')

stack traceback:

server/main.lua:43: in function 'LoadShop'

server/main.lua:10: in upvalue 'handler'

citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>

stack traceback:

[C]: in function 'error'

citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'

citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>`

Je ne c'est pas d'ou cela peut t'il venir et si cela impact la stabilité de cette extention

Merci pour votre travail 

Cordialement

**Comment by HumanTree92** [comment]
English please?
