### ISSUE TITLE
Error if shop database is empty

### ISSUE THREAD

**Issue by ElPumpo** [ESX-Org/esx_shops#37]

**Comment by Prophidys** [comment]
Do we need to empty the shops SQL and put all bread and water entries in basicneeds SQL ? (with a dependencies in basicneeds to shops ?). Or do we have to create a optional sql in shops for basic needs ? I want to help on this but I don't see how to manage that properly

**Comment by ElPumpo** [comment]
As I've said it's not viable to require basicneeds.

Same with esx_basicneeds, adding the `ALTER SHOPS` to its sql will make it require esx_shops, and I dont want that.

The solution is really easy, it's a matter of adding checks to make sure the table ain't empty, and if it is then handle it properly.

**Comment by JoeFlacko** [comment]
howcome i cant buy items from shop this is my code


SCRIPT ERROR: @es_extended/server/classes/player.lua:358: attempt to perform arithmetic on a nil value (field 'weight')
> getWeight (@es_extended/server/classes/player.lua:358)
> ref (@es_extended/server/classes/player.lua:365)
> handler (@esx_shops/server/main.lua:61)

**Comment by xdrahmahx** [comment]
> howcome i cant buy items from shop this is my code
> 
> SCRIPT ERROR: @es_extended/server/classes/player.lua:358: attempt to perform arithmetic on a nil value (field 'weight')
> 
> > getWeight (@es_extended/server/classes/player.lua:358)
> > ref (@es_extended/server/classes/player.lua:365)
> > handler (@esx_shops/server/main.lua:61)

same issue

**Comment by wil2005-development** [comment]
> > howcome i cant buy items from shop this is my code
> > SCRIPT ERROR: @es_extended/server/classes/player.lua:358: attempt to perform arithmetic on a nil value (field 'weight')
> > > getWeight (@es_extended/server/classes/player.lua:358)
> > > ref (@es_extended/server/classes/player.lua:365)
> > > handler (@esx_shops/server/main.lua:61)
> 
> same issue

Same issue

**Comment by emanuelkufrin** [comment]
> howcome i cant buy items from shop this is my code
> 
> SCRIPT ERROR: @es_extended/server/classes/player.lua:358: attempt to perform arithmetic on a nil value (field 'weight')
> 
> > getWeight (@es_extended/server/classes/player.lua:358)
> > ref (@es_extended/server/classes/player.lua:365)
> > handler (@esx_shops/server/main.lua:61)

Just add new column to table named weight and put it INT(11)
I did that, then it doesnt get me that error, but get me another one which i cant fix for few days 
SCRIPT ERROR: @esx_shops/server/main.lua:60: attempt to call a nil value (field 'canCarryItem')
