### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by ProxyAcid** [ESX-Org/esx_shops#41]
Getting this error when startup:

[ERROR] [MySQL] An critical error happens on MySQL for query "SELECT * FROM shops LEFT JOIN items ON items.name = shops.item {=}": An item with the same key has already been added.   at System.ThrowHelper.ThrowArgumentException (System.ExceptionResource resource) [0x0000b] in <0123fd5b1a1040fe9d70a7e0d4b28acb>:0

**Comment by AODeltaB** [comment]
Hello @ProxyAcid , you must use the last version of "es_extended", and be sure to execute CORRECTLY the SQL file, some modifications has been made in this file such the fact that there is nomore "id" column in Jobs or Item (for your case).
