### ISSUE TITLE
Invalid item "" found!

### ISSUE THREAD

**Issue by Prareric** [ESX-Org/esx_shops#42]
![image](https://user-images.githubusercontent.com/44494027/50363240-198fba00-056b-11e9-9e27-f0e36c9e7bfe.png)
![image](https://user-images.githubusercontent.com/44494027/50363274-3a580f80-056b-11e9-8ce6-8577bc469aa1.png)

**Comment by WafflezPlayz** [comment]
Are those items in your "items" table?

![image](https://user-images.githubusercontent.com/33784102/50443515-a89a2a80-08fb-11e9-8e27-dd62b1514bf9.png)
