### ISSUE TITLE
empty shop... 

### ISSUE THREAD

**Issue by OJits** [ESX-Org/esx_shops#44]
I know this is all over but I still cant seem to get it to work..

[shops]
https://i.imgur.com/XNagRKe.png

[Items]
https://i.imgur.com/6gK7Cyl.png

[in game]
https://i.imgur.com/qyoV9Om.jpg

**Comment by rpgsa** [comment]
Try changing your limit in your items database from -1 to 300 or something.
I have attached mine so you can look:
![itemstable](https://user-images.githubusercontent.com/43094090/50935788-1ea6a180-1465-11e9-9c70-2c7b05a8ad76.png)

**Comment by Ranger194** [comment]
i'm having the same problem, and i change all the limit and didnt fix it

**Comment by FRANkiller13** [comment]
@Ranger194 did you fix it ?.. because im looking too for this

**Comment by ElPumpo** [comment]
#13
