### ISSUE TITLE
add weapon to the shop

### ISSUE THREAD

**Issue by Tiborc** [ESX-Org/esx_shops#52]
Hello,

I'm looking for a solutions for add  weapon to the shops, basicly i want to add the jerry can. i have the "weapon_petrolcan" in the items and in the shops database, and it is working like a normal item(i can see it in the invertory) but it is not adding to the weapon wheel. Is it possible and if yes can somebody point me out where i need to look?

Thank You.

**Comment by ElPumpo** [comment]
No
