### ISSUE TITLE
Getting this error when entering the shop

### ISSUE THREAD

**Issue by JuannmaCh** [ESX-Org/esx_shops#55]
Hey! I just installed esx_shops in a fresh server and when i get into the shop it says:

Error resuming coroutine: @esx_shops/client/main.lua:168: attemp to call to a nil value (field 'ShowHelpNotification')
stack traceback:
        @esx_shops/client/main.lua:168: in function <@esx_shops/client/main.lua:163>

Any idea about how to fix this? It doesn't show anything, not even the shop.

Thanks!

**Comment by ElPumpo** [comment]
Update esx
