### ISSUE TITLE
Error when purchasing in shop!!

### ISSUE THREAD

**Issue by drezh** [ESX-Org/esx_shops#61]
I get this error when i buy something from a shop in console (F8).

![6a7d35a1f9dd44223642e454369e39d6](https://user-images.githubusercontent.com/46326894/67010734-8376e280-f0ee-11e9-8928-fcd07864fde6.png)

And this error in the server console
![7f64b4890f1bc2cecccf583d2c9da48a](https://user-images.githubusercontent.com/46326894/67010801-a6a19200-f0ee-11e9-8b39-0690dea8646c.png)

What is the problem?

**Comment by Mannot74** [comment]
> I get this error when i buy something from a shop in console (F8).
> 
> ![6a7d35a1f9dd44223642e454369e39d6](https://user-images.githubusercontent.com/46326894/67010734-8376e280-f0ee-11e9-8928-fcd07864fde6.png)
> 
> And this error in the server console
> ![7f64b4890f1bc2cecccf583d2c9da48a](https://user-images.githubusercontent.com/46326894/67010801-a6a19200-f0ee-11e9-8b39-0690dea8646c.png)
> 
> What is the problem?

Question, do you use the last master es_extended ? Because it break some plugin due to new function weight

**Comment by drezh** [comment]
> > I get this error when i buy something from a shop in console (F8).
> > ![6a7d35a1f9dd44223642e454369e39d6](https://user-images.githubusercontent.com/46326894/67010734-8376e280-f0ee-11e9-8928-fcd07864fde6.png)
> > And this error in the server console
> > ![7f64b4890f1bc2cecccf583d2c9da48a](https://user-images.githubusercontent.com/46326894/67010801-a6a19200-f0ee-11e9-8b39-0690dea8646c.png)
> > What is the problem?
> 
> Question, do you use the last master es_extended ? Because it break some plugin due to new function weight

Yepp, Someone else have the exact same problem as me. So it is something wrong with es_extended :)

**Comment by sutibci** [comment]
Any solutions for this?

**Comment by drezh** [comment]
> Any solutions for this?

The new es_extended update is the issue. Just wait for another update and it will be fixed hopefully :)

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/esx_shops/commit/4efea53b37479be788886a7d6dff5d29a9c9c478
