### ISSUE TITLE
esx_shops: server/main.lua:65: ')' expected (to close '(' at line 64) near 'else'

### ISSUE THREAD

**Issue by lpcv** [ESX-Org/esx_shops#66]
Hi I have a problem with the script when I start the server
I specify that es extended and on the last update no shops works

Error parsing script server/main.lua in resource esx_shops: server/main.lua:66: ')' expected (to close '(' at line 64) near 'xPlayer'

**Comment by lpcv** [comment]
Error parsing script server/main.lua in resource esx_shops: server/main.lua:65: ')' expected (to close '(' at line 64) near 'else'
Failed to load script server/main.lua.
Started resource esx_shops
es_extended: TriggerServerCallback => [esx_shops:requestDBItems] does not exist

**Comment by lpcv** [comment]
Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:403: server/classes/player.lua:358: attempt to perform arithmetic on a nil value (field 'weight')
stack traceback:
        server/classes/player.lua:358: in field 'getWeight'
        server/classes/player.lua:365: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>
Error running system event handling function for resource esx_shops: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:626: in field 'canCarryItem'
        server/main.lua:61: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>

**Comment by ElPumpo** [comment]
update esx

**Comment by lpcv** [comment]
error happens with the new update of Esx-shops that you did 1 hours ago

**Comment by nuttx74** [comment]
YEp...... same error with artifacte 2019-Oct-18 19:21 and upadte esx_shops

Started resource esx_status
Creating script environments for esx_shops
Error parsing script @esx_shops/server/main.lua in resource esx_shops: @esx_shops/server/main.lua:74: ')' expected (to close '(' at line 73) near 'else'
Failed to load script server/main.lua.

**Comment by ElPumpo** [comment]
update esx_shops then

**Comment by lpcv** [comment]
FR//
Re 
j'ai trouvé l'erreur il faut ajouter la colonne poids a la base de donne de es extended
EN//
Hi
I found the mistake you have to add the weight column to the database of es extended

**Comment by nuttx74** [comment]
esx-jobs has been corrected in (main.lua) (server and client)

server\main.lua
############################
-- can the player afford this item?
	if xPlayer.getMoney() >= price then
		-- can the player carry the said amount of x item?
		if sourceItem.limit ~= -1 and (sourceItem.count + amount) > sourceItem.limit then
			TriggerClientEvent('esx:showNotification', _source, _U('player_cannot_hold'))
		else
		if xPlayer.canCarryItem(itemName, amount) then
			xPlayer.removeMoney(price)
			xPlayer.addInventoryItem(itemName, amount)
			TriggerClientEvent('esx:showNotification', _source, _U('bought', amount, itemLabel, ESX.Math.GroupDigits(price)))
			xPlayer.showNotification(_U('bought', amount, itemLabel, ESX.Math.GroupDigits(price))
		else
			xPlayer.showNotification(_U('player_cannot_hold'))
		end
	else
		local missingMoney = price - xPlayer.getMoney()
		TriggerClientEvent('esx:showNotification', _source, _U('not_enough', ESX.Math.GroupDigits(missingMoney)))
		xPlayer.showNotification(_U('not_enough', ESX.Math.GroupDigits(missingMoney)))
	end
	end)
end)

**Comment by nuttx74** [comment]
@lpcv 
Salut .... J'avais déjà ajouté weight dans ma base de donnée.

![Annotation 2019-10-20 092624](https://user-images.githubusercontent.com/56788583/67160151-cec20880-f31b-11e9-80d7-8b7094a68d65.png)

**Comment by lpcv** [comment]
@nuttx74 
moi je parler du soucie avec Esx Shop 
Ton soucie toi ses avec esx Job ? 
Moi j'ai gardé l’ancienne version de Jobs
Tu a controlé d'avoir tout les item des jobs dans la base ?

**Comment by nuttx74** [comment]
@lpcv 
Oupps désolé je me suis trompé dans mon premier post.
l'erreur est bien généré par es_shops  
esx_shops/server/main.lua 

ERREUR
Started resource esx_status
Creating script environments for esx_shops
Error parsing script @esx_shops/server/main.lua in resource esx_shops: @esx_shops/server/main.lua:74: ')' expected (to close '(' at line 73) near 'else'
Failed to load script server/main.lua.

**Comment by lpcv** [comment]
@nuttx74 
ta pris la dernière version qui a étais modifier se matin ? de esx shop

**Comment by nuttx74** [comment]
@lpcv 
Ok good plus d'erreur ... avec les modif de ce matin..
esx_Shop de nouveau fonctionnel...

Par contre le esx_status n'afiche plus rien....

**Comment by ElPumpo** [comment]
People why are you removing the new code? It's not broken, you must update ESX and use the new SQL format in order for it to work, OR dont update esx

**Comment by lpcv** [comment]
@lpcv

Impec pour le shop par contre status je ne l'utilise pas

**Comment by nuttx74** [comment]
@lpcv 

C'est OK finalement pour esx_status ... j'avais testé avec esx_ladderhud ...
Finalement je suis revenu à ESX-Org\esx_status
Tous fonctionne bien...
Je me lance dans esx_property et esx_vehicleshope

**Comment by snakezdigital** [comment]
@ElPumpo i updated esx but i dont know which is the new format and every script now is broken all gives this error 

SCRIPT ERROR: @es_extended/server/classes/player.lua:358: attempt to perform arithmetic on a nil value (field 'weight')
> canCarryItem (@es_extended/server/classes/player.lua:365)
> handler (@es_extended/server/main.lua:282)

can you help me to fix this? kind regards

**Comment by TheLG181** [comment]
I have this error, how can help me?

ERROR: @esx_shops/server/main.lua:66: attempt to compare nil with number

**Comment by logandkns** [comment]
@ipcv je n'y arrive pas tu peut m'aider ?

**Comment by neryogaris** [comment]
esx_shop/client/main.lua:20: attempt to index a nil value field ref esx_shops/client/main.lua:20 handler es_extended/client/functions.lua:1113

**Comment by Keule0815061988** [comment]
SCRIPT ERROR: @esx_shops/server/main.lua:11: table index is nil
