### ISSUE TITLE
[Solved]Can not buy items from the store...

### ISSUE THREAD

**Issue by MiKPT** [ESX-Org/esx_shops#71]
Hey there.
When I go to buy an item in the shop blip, I can use the menu and all but when I confirm the purchase, it just goes back to the shop items, doesn't give me anything, and prints out the following error:
`SCRIPT ERROR @esx_shops\server\main.lua:67: attempt to compare nill with number`

Line 67 shows the following code:
`if sourceItem.limit ~= -1 and (sourceItem.count + amount) > sourceItem.limit then`

How would I go to fix this problem and what the heck is he considering as nill? Is it sourceItem.count ?

I also tried to remove this part of the code where the script checks if the player can carry the item, but with no avail as it asks me for *end* and there is actually no missing end AFAIK

Really appreciate any help at this point.
Thanks

**Comment by DayField** [comment]
you have the latest version of extended ?  Esx_ shops is not up to date for the new weight system.

**Comment by MiKPT** [comment]
Yhea, I found that out.

Great job btw devs lol

**Comment by ElPumpo** [comment]
solved? close it

**Comment by Dael180** [comment]
Good morning, excuse me. I have the same problem and I could not solve it after seeing many posts including this one that is my problem, but without error in console. Can somebody help me? Thanks in advance
