### ISSUE TITLE
ESX_Shops broken cant buy items

### ISSUE THREAD

**Issue by ZeeDijkRP** [ESX-Org/esx_shops#72]
Hi, 
I'm having troubles with esx_shops. the menu shows up correctly but when i try to buy something it just does not give me anything. the money doesnt get deleted from my account to. in F8 I get no errors. i have tried to reinstal the script but that doesnt work. it keeps doeing the same.

thx in advance

**Comment by reeperk** [comment]
I have this problem as well! I get this error out of it in my Console:
[91mSCRIPT ERROR: @es_extended/server/classes/player.lua:358: attempt to perform arithmetic on a nil value (field 'weight')[0m
[93m> getWeight[0m ([36m@es_extended/server/classes/player.lua[0m:358)
[93m> ref[0m ([36m@es_extended/server/classes/player.lua[0m:365)
[93m> handler[0m ([36m@esx_shops/server/main.lua[0m:61)

**Comment by ZeeDijkRP** [comment]
boy why you close wtf

**Comment by ZeeDijkRP** [comment]
@reeperk  i dont have any error it just doesnot work

**Comment by emanuelkufrin** [comment]
Yea same error, and this dude dont reply, he just close thread idk why? ? ?
