### ISSUE TITLE
Cant buy items from shop

### ISSUE THREAD

**Issue by JoeFlacko** [ESX-Org/esx_shops#74]
Ive tried reinstalling the app aswell as placing items in my items tab in the database may it be because i have more items in the item list than i have down on my shop?

SCRIPT ERROR: @es_extended/server/classes/player.lua:358: attempt to perform arithmetic on a nil value (field 'weight')
> getWeight (@es_extended/server/classes/player.lua:358)
> ref (@es_extended/server/classes/player.lua:365)
> handler (@esx_shops/server/main.lua:61)

**Comment by Onkelplay2** [comment]
I have the same Problem.
