### ISSUE TITLE
Attempt to index a nil value

### ISSUE THREAD

**Issue by vicciusomerta** [ESX-Org/esx_shops#75]
Hi, i get this errors, how can i fix them ? 

1st Error : 

SCRIPT ERROR: @esx_shops/server/main.lua:43: attempt to index a nil value (field '?')
> handler (@esx_shops/server/main.lua:10)
![image](https://user-images.githubusercontent.com/28043209/68393766-f95def00-016c-11ea-93a5-2d043f612ee8.png)

2nd Error : 

SCRIPT ERROR: @esx_shops/server/main.lua:43: attempt to index a nil value (field '?')
> fn (@esx_shops/server/main.lua:18)
![image](https://user-images.githubusercontent.com/28043209/68394605-7473d500-016e-11ea-85b3-0307e7779f54.png)

**Comment by harpreet9629** [comment]
I am getting same error :(
