### ISSUE TITLE
some shops blank

### ISSUE THREAD

**Issue by numpty9989** [ESX-Org/esx_shops#78]
I basically have installed the shops and sometimes the shop Just shows the header SHOP and no items and sometimes shows all the items.. if you log off and log back in occasionally the shops work like 33% of the time.. there is NO errors in the console or F8 log and all shops are letting you buy food when they do work any idea how to fix?

**Comment by numpty9989** [comment]
i have tried following tis  https://github.com/ESX-Org/esx_shops/pull/53 and its jst not working please i hope u can help thanks

**Comment by spider1987** [comment]
The problem is with the database to be exact the table "items">`weight`

If you remove them this works again

**Comment by numpty9989** [comment]
It used to be limit so changed to weight and still having the issue :(. Have even tried different versions of shops with no luck

**Comment by numpty9989** [comment]
so should it be limit or weight??? just to be sure as some people have it as limit others weight so I am confused.. as your the developer you can clarify it and I can re test and see if I fix it
