### ISSUE TITLE
You can buy more than you can carry

### ISSUE THREAD

**Issue by Roo7K1d** [ESX-Org/esx_shops#84]
I found this issue with the newest version of esx_shops.
Since the new es_extended is using 'weight' instead of 'limit' it causes problems like being able to buy more than you can carry. I would be very happy to see this fixed.

You can see the error here:

![image](https://user-images.githubusercontent.com/47664151/76703094-12544f00-66cf-11ea-8761-b1e337d5de95.png)

and

line 86 in server.lua

`if sourceItem.limit == -1 and (sourceItem.count + amount) > sourceItem.limit then
			TriggerClientEvent('esx:showNotification', _source, _U('player_cannot_hold'))`

**Comment by YisusTM01** [comment]
You using latest es_extended or older es_extended?

**Comment by Roo7K1d** [comment]
> You using latest es_extended or older es_extended?

I'm using the latest version of es_extended as well as the latest version of esx_shops.
