### ISSUE TITLE
How can i make a shop for police only

### ISSUE THREAD

**Issue by N1ma6** [ESX-Org/esx_shops#89]
The title says it all

**Comment by nutcracker89** [comment]
i can maybe help you , have one on my server org made from esx_shops. i use two esx_shop one is normal and one is job only

**Comment by N1ma6** [comment]
that what i need but how do i set the premision

**Comment by N1ma6** [comment]
> i can maybe help you , have one on my server org made from esx_shops. i use two esx_shop one is normal and one is job only

that what i need but how do i set the premision

**Comment by nutcracker89** [comment]
> 
> 
> > i can maybe help you , have one on my server org made from esx_shops. i use two esx_shop one is normal and one is job only
> 
> that what i need but how do i set the premision

here try this one
https://github.com/nutcracker89/esx_policeshop/

**Comment by N1ma6** [comment]
I can't get it working when I get to the coords nothing shows up

I did start it in server.cfg

**Comment by N1ma6** [comment]
![image](https://user-images.githubusercontent.com/63562255/82373706-3eb58000-9a1e-11ea-998c-9ed9bec6c87d.png)

**Comment by N1ma6** [comment]
Thats the error i get

**Comment by nutcracker89** [comment]
> 
> 
> Thats the error i get

are you using the latest es_extended if so then in wont work

**Comment by N1ma6** [comment]
yes but can i get it working with it?

**Comment by nutcracker89** [comment]
> 
> 
> yes but can i get it working with it?
this one works with the new es_extended 
https://github.com/nutcracker89/esx_policeshop-for-latest-es_extended

**Comment by N1ma6** [comment]
Thanks
